FROM python:3.10-alpine

RUN mkdir -p /home/flask_app/EnviarCorreo
WORKDIR /home/flask_app/EnviarCorreo

COPY requirements.txt ./
RUN apk update \
    && apk add --virtual build-deps gcc python3-dev musl-dev \
    && apk add --no-cache mariadb-dev

RUN pip install --no-cache-dir -r requirements.txt
RUN apk add --update bash && rm -rf /var/cache/apk/*

COPY ./EnviarCorreo ./

RUN apk del build-deps

COPY wait-for-it.sh wait-for-it.sh
RUN chmod +x wait-for-it.sh

ENV FLASK_APP app.py
