FROM python:3.10-alpine

RUN mkdir -p /home/flask_app/EnviarCorreo
WORKDIR /home/flask_app/EnviarCorreo

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN apk add --update bash && rm -rf /var/cache/apk/*

COPY ../../EnviarCorreo ./

COPY wait-for-it.sh wait-for-it.sh
RUN chmod +x wait-for-it.sh

ENV FLASK_APP app.py
