version: "3.5"
services:
  api-enviarCorreo:
    environment:
      - GOOGLE_APPLICATION_SUB_NOTIFICAR=projects/grupo4-cloud-368923/subscriptions/Notificar-sub
    container_name: api-enviarCorreo
    image: api_enviar_correo:1
    build:
      context: ./
      dockerfile: Dockerfile-EnviarCorreo
    ports:
      - "5002:5002"
    restart: always
    command: ["gunicorn", "-b", ":5002", "--access-logfile", "-", "--error-logfile", "-", "wsgi:app"]