version: "3.5"
services:
  api-convertirArchivo:
    environment:
      - SERVER_KAFKA=10.128.0.2:9092
      - GOOGLE_APPLICATION_CREDENTIALS=credencial_google.json
      - GOOGLE_APPLICATION_BUCKET_NAME=grupo4-cloud-366900-archivos
    container_name: api-convertirArchivo
    image: api_convertir_archivo:1
    build:
      context: ./
      dockerfile: Dockerfile-ConvertirArchivo
    ports:
      - "5001:5001"
    restart: always
    command: ["./wait-for-it.sh", "10.128.0.2:9092", "-t", "50", "--", "gunicorn", "--bind", "0.0.0.0:5000" , "--timeout", "120", "wsgi:app"]